# Generated by Django 4.2.1 on 2023-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="volunteer",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
