# Generated by Django 4.2.1 on 2023-05-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0003_alter_profile_volunteer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="volunteer", new_name="userType",
        ),
    ]
