# Generated by Django 4.2.1 on 2023-06-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0004_rename_volunteer_profile_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventName", models.CharField(max_length=100)),
                ("eventDescription", models.CharField(max_length=400)),
                ("eventType", models.CharField(max_length=50)),
                ("noOfPositions", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(max_length=400, null=True)),
                ("eventDate", models.DateField(null=True)),
                ("startTime", models.CharField(max_length=400, null=True)),
                ("endTime", models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="userType",
            field=models.PositiveIntegerField(
                choices=[(0, "-----"), (1, "Volunteer"), (2, "Organizer")], default=0
            ),
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.CharField(max_length=500)),
                ("highLevelEducation", models.CharField(max_length=30)),
                ("event", models.ManyToManyField(to="credentials.event")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credentials.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orgName", models.CharField(max_length=50)),
                ("orgDivision", models.CharField(max_length=50)),
                ("orgRating", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credentials.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credentials.organization",
            ),
        ),
    ]
